DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Models/transaccion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CajeroWeb.Models
{
    public class transaccion
    {
        // Clase que se utiliza para gestionar las transacciones a realizar por el cajero ATM
        //Campos (privados) de la clase
        private String sNumeroTarjeta;
        private double fSaldo;
        //Constructor de clase que solo acepta un parametro de tipo String
        public transaccion(String tarjeta)
        {
            sNumeroTarjeta = tarjeta;
            fSaldo = 500;
        }
        //Constructor de clase que acepta dos parametros: String y double.
        //Puede haber tantos constructores como se necesiten, pero c/definición debe tener
        // una firma (lista y orden de tipos de datos en parametros) diferente.
        public transaccion(String tarjeta, double saldo)
        {
            sNumeroTarjeta = tarjeta;
            fSaldo = saldo;
        }
        //Implementa métodos (get y set) para acceder a campos de clase
        public double getSaldo()
        {
            return fSaldo;
        }
        public void setSaldo(double saldo)
        {
            fSaldo = saldo;
        }
        public String getNumTarjeta()
        {
            return sNumeroTarjeta;
        }
        public void setNumTarjeta(String tarjeta)
        {
            sNumeroTarjeta = tarjeta;
        }
        public void transferenciaNacional(double monto)
        {
            fSaldo = fSaldo - monto;
        }
        public void transferenciaInternacional(double monto)
        {
            fSaldo = fSaldo - monto;
        }
    }
}

DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CajeroWeb.Models;

namespace CajeroWeb.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string sNumeroTarjeta, string sNumeroPIN)
        {
            double sSaldo;
            string numero;
            transaccion nuevaTransaccion = new transaccion(sNumeroTarjeta);
            if (sNumeroTarjeta == "123456" && sNumeroPIN == "654321")
            {
                numero = nuevaTransaccion.getNumTarjeta();
                sSaldo = nuevaTransaccion.getSaldo();
                return Redirect("~/Menu/Menu?sNumeroTarjeta=" + sNumeroTarjeta + "&sSaldo=" + sSaldo);
            }
            else
            {
                // Si el numero de pin o de tarjeta no corresponde, entonces se
                // procede a mostrar un mensaje de error
                ViewBag.Error = "Error en número de tarjeta o número de PIN. Verifique";
                return View();
            }
        }
    }
}

DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Controllers/InternacionalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CajeroWeb.Models;

namespace CajeroWeb.Controllers
{
    public class InternacionalesController : Controller
    {
        // GET: Internacionales
        public ActionResult Internacionales(string sNumeroTarjeta, double sSaldo)
        {
            ViewBag.sNumeroTarjeta = sNumeroTarjeta;
            ViewBag.sSaldo = sSaldo;
            return View();
        }
        [HttpPost]
        public ActionResult Internacionales(string sNumeroTarjeta, double sSaldo, double cantidad)
        {
            double Saldo;
            //Se crea una instancia de la clase transacción y se le envían dos parámetros
            transaccion nuevaTransaccion = new transaccion(sNumeroTarjeta, sSaldo);
            if (cantidad > 0)
            {
                nuevaTransaccion.transferenciaInternacional(cantidad);
            }
            sSaldo = nuevaTransaccion.getSaldo();
            ViewBag.sNumeroTarjeta = nuevaTransaccion.getNumTarjeta();
            ViewBag.sSaldo = nuevaTransaccion.getSaldo();
            return Redirect("~/Menu/Menu?sNumeroTarjeta=" + sNumeroTarjeta + "&sSaldo=" + sSaldo);
        }
    }



}

DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CajeroWeb.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult Menu(string sNumeroTarjeta, double sSaldo)
        {
            ViewBag.sNumeroTarjeta = sNumeroTarjeta;
            ViewBag.sSaldo = sSaldo;
            return View();
        }
    }
}

DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Controllers/NacionalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CajeroWeb.Models;

namespace CajeroWeb.Controllers
{
    public class NacionalesController : Controller
    {
        // GET: Nacionales
        public ActionResult Nacionales(string sNumeroTarjeta, double sSaldo)
        {
            ViewBag.sNumeroTarjeta = sNumeroTarjeta;
            ViewBag.sSaldo = sSaldo;
            return View();
        }
        [HttpPost]
        public ActionResult Nacionales(string sNumeroTarjeta, double sSaldo, double cantidad)
        {
            double Saldo;
            //Se crea una instancia de la clase transacción y se le envían dos parámetros
            transaccion nuevaTransaccion = new transaccion(sNumeroTarjeta, sSaldo);
            if (cantidad > 0)
            {
                nuevaTransaccion.transferenciaNacional(cantidad);
            }
            sSaldo = nuevaTransaccion.getSaldo();
            ViewBag.sNumeroTarjeta = nuevaTransaccion.getNumTarjeta();
            ViewBag.sSaldo = nuevaTransaccion.getSaldo();
            return Redirect("~/Menu/Menu?sNumeroTarjeta=" + sNumeroTarjeta + "&sSaldo=" + sSaldo);
        }
    }
}
       

DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Controllers/SaldoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CajeroWeb.Models;

namespace CajeroWeb.Controllers
{
    public class SaldoController : Controller
    {
        // GET: Saldo
        public ActionResult Saldo()
        {
            var tarjeta = "123456";
            var saldo = 500;


            ViewBag.Tarjeta = tarjeta;
            ViewBag.Saldo = saldo;

            return View();
        }
    }
}

DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Views/Menu/Menu.cshtml
@{
    ViewBag.Title = "Menu";
}
<article class="middle">
    <h2>Bienvenido</h2>
    Innovando las transacciones en línea, ponemos a su disposición el cajero ATM online
    donde podrá realizar sus pagos y transferencias en línea de una forma rápida y fácil
    siempre con la calidad y la confianza que nos caracterizan. Realice sus transacciones
    desde la comodidad de su hogar las 24 horas del día los 7 días de la semana.
</article>
<nav class="right">
    <ul>
        <li>
            @Html.ActionLink("Transferencias nacionales", "Nacionales", "Nacionales", new
            {
           sNumeroTarjeta = ViewBag.sNumeroTarjeta,
                sSaldo = ViewBag.sSaldo
            }, null)
        </li>
        <li>
            @Html.ActionLink("Transferencias internacionales", "Internacionales", "Internacionales", new
            {
           sNumeroTarjeta = ViewBag.sNumeroTarjeta,
           sSaldo = ViewBag.sSaldo
            }, null)
        </li>
        <li>
            @Html.ActionLink("Pagos de Servicios", "Menuopcion", "Home", new { opcion = 3 },
           null)
        </li>
        <li>
            @Html.ActionLink("Saldo", "Saldo", "Saldo", new
       {
           sNumeroTarjeta= ViewBag.sNumeroTarjeta,
           sSaldo = ViewBag.sSaldo
       }, null)
           
        </li>
    </ul>
</nav>

DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Views/Nacionales/Nacionales.cshtml
@{
    ViewBag.Title = "Nacionales";
}
@{
    var bancos = new List<SelectListItem>(){
 new SelectListItem { Text = "Banco Agrícola", Value = "0" },
 new SelectListItem { Text = "Banco de América Central", Value = "1" },
 new SelectListItem { Text = "Banco Davivienda", Value = "2", Selected = true },
 new SelectListItem { Text = "Banco Cuscatlan", Value = "3" }
};
}
<article class="middle">
    <h2>Bienvenido</h2>
    Innovando las transacciones en línea, ponemos a su disposición el cajero ATM online
    donde podrá realizar sus pagos y transferencias en línea de una forma rápida y fácil
    siempre con la calidad y la confianza que nos caracterizan. Realice sus transacciones
    desde la comodidad de su hogar las 24 horas del día los 7 días de la semana.
    <div class="credenciales">
        <div class="bloque">
            <label class="etiqueta">Tarjeta #:</label>
            <label class="control">@ViewBag.sNumeroTarjeta</label>
        </div>
        <div class="clear"></div>
        <div class="bloque">
            <label class="etiqueta">Saldo:</label>
            <label class="control">@ViewBag.sSaldo</label>
        </div>
        <div class="clear"></div>
        <div class="bloque">
            @Html.DropDownList("misbancos", bancos);
        </div>
        <div class="bloque">
            @Html.Label("Cantidad:", new { @class = "etiqueta" });
            @Html.Editor("cantidad", "", new { @class = "control" });
        </div>
        <div class="bloque">
            <button type="submit" ID="btnEntrar" CssClass="submit" runat="server"
                    onclick="location.href('@Url.Action("NacionalesNuevo", "Nacionales")')">
                Ingresar
            </button>
        </div>
        <div class="clear"></div>
    </div>
    @using (Html.BeginForm())
    {
        <div class="bloque">
            <label class="error">@ViewBag.Error</label>
        </div>
    }
</article>
<nav class="right">
    <ul>
        <li>
            @Html.ActionLink("Transferencias nacionales", "someaction", "somecontroller",
           new { id = "123" }, null)
        </li>
        <li>
            @Html.ActionLink("Transferencias internacionales", "someaction",
           "somecontroller", new { id = "123" }, null)
        </li>
        <li>
            @Html.ActionLink("Pagos de Servicios", "someaction", "somecontroller", new
            {
                id = "123"
            }, null)
        </li>
        <li>
            @Html.ActionLink("Verificar saldos", "someaction", "somecontroller", new
            {
                id = "123"
            }, null)
        </li>
    </ul>
</nav>

DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Views/Saldo/Saldo.cshtml
@{
    ViewBag.Title = "Saldo";
    ViewBag.sNumeroTarjeta = "123456";
    ViewBag.sSaldo = 500;
}

<article class="middle">
    <h2>Bienvenido</h2>
    Innovando las transacciones en línea, ponemos a su disposición el cajero ATM online
    donde podrá realizar sus pagos y transferencias en línea de una forma rápida y fácil
    siempre con la calidad y la confianza que nos caracterizan. Realice sus transacciones
    desde la comodidad de su hogar las 24 horas del día los 7 días de la semana.


    <div class="credenciales">
        <div class="bloque">
            <label class="etiqueta">Tarjeta #:</label>
            <label class="control">@ViewBag.sNumeroTarjeta</label>
        </div>
        <div class="clear"></div>
        <div class="bloque">
            <label class="etiqueta">Saldo:</label>
            <label class="control">@ViewBag.sSaldo</label>
        </div>
        
 
        
        <div class="clear"></div>
    </div>
    @using (Html.BeginForm())
    {
        <div class="bloque">
            <label class="error">@ViewBag.Error</label>
        </div>
    }
</article>
<nav class="right">
    <ul>
        <li>
            @Html.ActionLink("Transferencias Nacionales", "someaction", "somecontroller",
           new { id = "123" }, null)
        </li>
        <li>
            @Html.ActionLink("Transferencias internacionales", "someaction",
           "somecontroller", new { id = "123" }, null)
        </li>
        <li>
            @Html.ActionLink("Pagos de Servicios", "someaction", "somecontroller", new
            {
                id = "123"
            }, null)
        </li>
        <li>
            @Html.ActionLink("Verificar saldos", "someaction", "somecontroller", new
            {
                id = "123"
            }, null)
        </li>
    </ul>
</nav>

DR231900_Guia7/Guia7/CajeroWeb/CajeroWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Transacciones Cajero ATM</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <form id="form1" method="post">
        <section id="wrap">
            <section id="top"></section>
            <section id="content">
                <header class="header">
                    <h1><a href="#">Cajero ATM</a></h1>
                    <h2>Transacciones online</h2>
                </header>
                <article class="breadcrumbs">@Html.ActionLink("INICIO", "/")</article>
                @RenderBody()
                <article id="clear"></article>
            </section>
            <section id="bottom"></section>
        </section>
        </section>
        </section>
    </form>
    <footer id="footer">
        <a href="http://www.udb.edu.sv">Universidad Don Bosco</a>
    </footer>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>